# Networking projects
cmake_minimum_required(VERSION 3.28)

# add_subdirectory(AgentService) # disabled
add_subdirectory(AsioHttpServer)
add_subdirectory(AsioTcpServer)
add_subdirectory(P2pClient)
add_subdirectory(P2pServer)
add_subdirectory(SystemPathTest)
add_subdirectory(TestServer)
add_subdirectory(ThreadPoolClient)
# add_subdirectory(HttpServerApp) # disabled
